// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_chiangmai.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tPb9rysfJ89BoxfdYZx77HH7xbz1MuQ',
    appId: '1:152859479675:android:529eaab5abf749a96e9cde',
    messagingSenderId: '152859479675',
    projectId: 'restaurant-orderapps',
    storageBucket: 'restaurant-orderapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TGV5D_bt3RntkP4fkwVtAbHMQjIt6WI',
    appId: '1:152859479675:ios:cc571f70d1914d876e9cde',
    messagingSenderId: '152859479675',
    projectId: 'restaurant-orderapps',
    storageBucket: 'restaurant-orderapps.appspot.com',
    iosClientId: '152859479675-bo2g2bbkp1qrc317k49dkapr7bs1j6s5.apps.googleusercontent.com',
    iosBundleId: 'dk.wejeo.restaurantorderapp.chiangmai',
  );
}
